// <auto-generated />
namespace MigraineDiaryMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ShootingInTheDark : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShootingInTheDark));
        
        string IMigrationMetadata.Id
        {
            get { return "201301280105533_ShootingInTheDark"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
