// <auto-generated />
namespace MigraineDiaryMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddTablesForSymptom_Medication_Dosage_Ingredient_and_UnitOfMeasurement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTablesForSymptom_Medication_Dosage_Ingredient_and_UnitOfMeasurement));
        
        string IMigrationMetadata.Id
        {
            get { return "201301272234271_AddTablesForSymptom_Medication_Dosage_Ingredient_and_UnitOfMeasurement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
