// <auto-generated />
namespace MigraineDiaryMVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MedicationToIngredientModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MedicationToIngredientModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201301280000347_MedicationToIngredientModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
